import tkinter as tk
from tkinter import ttk
root=tk.Tk()
root.title("title")
root.geometry("600x300")
root.columnconfigure(0,weight=1)
root.columnconfigure(1,weight=1)
root.columnconfigure(2,weight=1)
root.columnconfigure(3,weight=1)
root.columnconfigure(4,weight=1)
root.columnconfigure(5,weight=1)
root.columnconfigure(6,weight=1)
root.columnconfigure(7,weight=1)
root.columnconfigure(8,weight=1)
root.columnconfigure(9,weight=1)
root.columnconfigure(10,weight=1)
root.columnconfigure(11,weight=1)
root.columnconfigure(12,weight=1)
root.rowconfigure(0,weight=1)
root.rowconfigure(1,weight=1)
root.rowconfigure(2,weight=1)
root.rowconfigure(3,weight=1)
root.rowconfigure(4,weight=1)
root.rowconfigure(5,weight=1)
root.rowconfigure(6,weight=1)
root.rowconfigure(7,weight=1)
root.rowconfigure(8,weight=1)
root.rowconfigure(9,weight=1)
root.rowconfigure(10,weight=1)
root.rowconfigure(11,weight=1)
root.rowconfigure(12,weight=1)
main_frame_label=tk.Label(text="мое приложение")
main_frame_label.grid(row=0, column=5)
main_frame_entry=ttk.Entry()
main_frame_entry.grid(row=1, column=5)
main_frame_button=ttk.Button(text="поиск")
main_frame_button.grid(row=2, column=5)
button_back=ttk.Button(text="back")
button_back.grid(row=0, column=0)
image_author=tk.PhotoImage()
label_author=tk.Label()
label_author.grid(row=0, column=12)
label_author=image_author
image_1=tk.PhotoImage()
label_1=tk.Label()
label_1.grid(row=12, column=1)
label_1=image_1
image_2=tk.PhotoImage()
label_2=tk.Label()
label_2.grid(row=12, column=4)
label_2=image_2
image_3=tk.PhotoImage()
label_3=tk.Label()
label_3.grid(row=12, column=8)
label_3=image_3
button_1=ttk.Button()
button_1.grid(row=10, column=3)
button_2=ttk.Button()
button_2.grid(row=10, column=6)
button_3=ttk.Button()
button_3.grid(row=10, column=11)
root.mainloop()
